on:
  pull_request:
  push:

name: backwards compatibility

permissions:
  contents: read

jobs:
  roave_bc_check:
    uses: yiisoft/actions/.github/workflows/bc.yml@master
    with:
      composer-require-options: '--with-all-dependencies --ignore-platform-req=ext-wincache --ignore-platform-req=php --no-progress --ansi'
      php: '["8.4"]'
