on:
  pull_request:
  push:
    branches:
      - "master"

name: mutation test

jobs:
  mutation:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    env:
      extensions: curl, fileinfo, mbstring, openssl, wincache

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - windows-latest

        php:
          - "7.4"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          extensions: ${{ env.extensions }}
          ini-values: memory_limit=-1
          coverage: "pcov"
          tools: composer:v2

      - name: Update composer
        run: composer self-update

      - name: Choco install 7zip
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install 7zip

      - uses: suisei-cn/actions-download-file@v1
        id: wincache
        name: Download WinCache
        with:
          url: "https://netcologne.dl.sourceforge.net/project/wincache/development/wincache-2.0.0.8-dev-7.4-nts-vc15-x64.exe"
          target: C:\tools\php\ext

      - name: Install WinCache
        run: |
          cd C:\tools\php\ext
          7z e -y wincache-2.0.0.8-dev-7.4-nts-vc15-x64.exe

      - name: Update php.ini
        run: |
          cd C:\tools\php
          echo extension=php_wincache.dll >> php.ini
          echo wincache.enablecli=1 >> php.ini

      - name: Determine composer cache directory
        run: echo "COMPOSER_CACHE_DIR=~\AppData\Local\Composer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Cache dependencies installed with composer
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php }}-composer-

      - name: Install dependencies with composer
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run infection
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          vendor/bin/roave-infection-static-analysis-plugin -j2 --git-diff-filter=A --git-diff-base=origin/$GITHUB_BASE_REF --logger-github --ignore-msi-with-no-mutations --only-covered
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
